### PR TITLE
add two papers about diagnoisis and tuning

### PR DESCRIPTION
**Pull request by AntiTopQuark**

### CODE REVIEW

**Comment by lonng** [comment]
@AntiTopQuark Thanks for you contribution. Please change the README.md as well to index the added papers.

BTW, please use lower-case as the file name. And you can refer the other files

**Comment by lonng** [comment]
I have updated my document and the index will be generated tomorrow automatically.

**Comment by AntiTopQuark** [comment]
> @AntiTopQuark Thanks for you contribution. Please change the README.md as well to index the added papers.
> 
> BTW, please use lower-case as the file name. And you can refer the other files

Thanks for your review~

**Comment by lonng** [comment]
Added via commit https://github.com/lonng/db-papers/commit/806e0564e2f0f5c77a1f8b80b0bad319adeb6b6f

I will close this PR.

**Comment by lonng** [comment]
@AntiTopQuark Sorry for the current contribution workflow shortage causes your PR has been closed (the current index was generated by script automatically) and I will refine the contribution way to compatible both manual update and bot generating.

**Comment by AntiTopQuark** [comment]
> @AntiTopQuark Sorry for the current contribution workflow shortage causes your PR has been closed (the current index was generated by script automatically) and I will refine the contribution way to compatible both manual update and bot generating.

Thank you, I will continue to contribute if I come across interesting papers in the future.

**Comment by lonng** [comment]
@AntiTopQuark Thanks again.

**Pull request closed without merging**
